name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build ğŸšš
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo ğŸ“‚
        uses: actions/checkout@v3

      - name: Setup Node ğŸ‘¨â€ğŸ’»
        uses: actions/setup-node@v3

      - name: Install dependencies ğŸ”§
        uses: bahmutov/npm-install@v1

      - name: Build project ğŸ“¦
        run: npm run build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./build

  deploy:
    name: Deploy ğŸš€
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Download artifact ğŸ“©
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./build

      - name: Deploy to GitHub Pages ğŸš€ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build